driver:
  name: dokken
  # privileged is required otherwise the container doesn't boot right
  # privileged: true
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    privileged: true
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN /bin/yum install -y net-tools wget
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    privileged: true
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    platform: ubuntu
    privileged: true
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
- name: default
  run_list:
  - recipe[pm2_app::default]
  attributes:
